general {
    immediate_render = true
}

background {
    path = ~/Pictures/wallpapers/EOS02.jpg
    blur_passes = 2
    blur_size = 6
    brightness = 0.65 
}

input-field {
    monitor =
    size = 300, 30
    outline_thickness = 0
    dots_size = 0.25
    dots_spacing = 0.55
    dots_center = true
    dots_rounding = -1
    outer_color = rgba(0, 0, 0, 0)
    inner_color = rgba(0, 0, 0, 0)
    font_color = rgba(242, 243, 244, 0.75)
    fade_on_empty = false
    placeholder_text =
    hide_input = false
    check_color = rgba(204, 136, 34, 0)
    fail_color = rgba(204, 34, 34, 0)
    fail_text = $FAIL <b>($ATTEMPTS)</b>
    fail_transition = 300
    capslock_color = -1
    bothlock_color = -1
    invert_numlock = false
    swap_font_color = false
    position = 0, -468
    halign = center
    valign = center
}

label {
  monitor = 
  text = cmd[update:1000] ~/.config/hypr/scripts/playerctl.sh
  color = rgba(242, 243, 244, 0.75)
  font_size = 14
  font_family = Inter 
  position = 20, 512
  halign = left
  valign = center
}

label {
  monitor =
  text = cmd[update:1000] echo "$(~/.config/hypr/scripts/network-status)‎"
  color = rgba(242, 243, 244, 0.75)
  font_size = 16
  font_family = Inter
  position = -35, 512
  halign = right
  valign = center
}

label {
  monitor =
  text = cmd[update:1000] echo "$(date +"%A, %B %d")"
  color = rgba(242, 243, 244, 0.75)
  font_size = 20
  font_family = Inter Medium
  position = 0, 405
  halign = center
  valign = center
}

label {
  monitor = 
  text = cmd[update:1000] echo "$(date +"%k:%M")"
  color = rgba(242, 243, 244, 0.75)
  font_size = 93
  font_family = Inter Bold
  position = 0, 310
  halign = center
  valign = center
}


label {
    monitor =
    text = $USER
    color = rgba(242, 243, 244, 0.75)
    font_size = 12
    font_family = Inter Bold
    position = 0, -407
    halign = center
    valign = center
}

label {
    monitor =
    text = Touch ID or Enter Password
    color = rgba(242, 243, 244, 0.75)
    font_size = 10
    font_family = Inter
    position = 0, -438
    halign = center
    valign = center
}


